<?xml version="1.0" encoding="ISO-8859-1"?>
<!--CONTROL-FACILITY-SCR.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:include href="CONTROL-FACILITY-CTX.XSL"/>
<xsl:template match="CONTROL-FACILITY">
<table align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="608"><span class="screenid">FAC004</span></td>
<!--<td width="24"><span class="white">M</span></td>
<td width="24"><span class="white">A</span></td>
<td width="24"><span class="white">N</span></td>
<td width="24"><span class="white">T</span></td>
<td width="24"><span class="white">I</span></td>
<td width="272"><span class="white">S</span></td>-->
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="240"/>
<td width="400"><span class="title">FACILITY&#160;SELECTION</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="120"><span class="white"><a href="javascript:pressKey('@KEY:PF1');">Run&#160;A&#160;Program</a></span></td>
<td width="152"><span class="white">.................</span></td>
<td width="48"><span class="white">1</span></td>
<td width="176"><span class="white"><a href="javascript:pressKey('@KEY:PF13');">Edit&#160;MANTIS&#160;Messages</a></span></td>
<td width="104"><span class="white">...........</span></td>
<td width="32"><span class="white">13</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="160"><span class="white"><a href="javascript:pressKey('@KEY:PF2');">Display&#160;A&#160;Prompter</a></span></td>
<td width="112"><span class="white">............</span></td>
<td width="48"><span class="white">2</span></td>
<td width="160"><span class="white"><a href="javascript:pressKey('@KEY:PF14');">Directory&#160;Facility</a></span></td>
<td width="120"><span class="white">.............</span></td>
<td width="32"><span class="white">14</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="144"><span class="white"><a href="javascript:pressKey('@KEY:PF3');">Design&#160;A&#160;Program</a></span></td>
<td width="128"><span class="white">..............</span></td>
<td width="48"><span class="white">3</span></td>
<td width="216"><span class="white"><a href="javascript:pressKey('@KEY:PF15');">Universal&#160;Export&#160;Facility</a></span></td>
<td width="64"><span class="white">......</span></td>
<td width="32"><span class="white">15</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="136"><span class="white"><a href="javascript:pressKey('@KEY:PF4');">Design&#160;A&#160;Screen</a></span></td>
<td width="136"><span class="white">...............</span></td>
<td width="360"><span class="white">4</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="184"><span class="white"><a href="javascript:pressKey('@KEY:PF5');">Design&#160;A&#160;File&#160;Profile</a></span></td>
<td width="88"><span class="white">.........</span></td>
<td width="360"><span class="white">5</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="152"><span class="white"><a href="javascript:pressKey('@KEY:PF6');">Design&#160;A&#160;Prompter</a></span></td>
<td width="120"><span class="white">.............</span></td>
<td width="360"><span class="white">6</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="184"><span class="white"><a href="javascript:pressKey('@KEY:PF7');">Design&#160;A&#160;User&#160;Profile</a></span></td>
<td width="88"><span class="white">.........</span></td>
<td width="48"><span class="white">7</span></td>
<td width="280"><span class="white"><a href="javascript:pressKey('@KEY:PF19');">MANTIS&#160;Clusters&#160;Locking&#160;Facility</a>.</span></td>
<td width="32"><span class="white">19</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="160"><span class="white"><a href="javascript:pressKey('@KEY:PF8');">Design&#160;A&#160;Interface</a></span></td>
<td width="112"><span class="white">............</span></td>
<td width="48"><span class="white">8</span></td>
<td width="136"><span class="white"><a href="javascript:pressKey('@KEY:PF20');">Search&#160;Facility</a></span></td>
<td width="144"><span class="white">................</span></td>
<td width="32"><span class="white">20</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="208"><span class="white"><a href="javascript:pressKey('@KEY:PF9');">Design&#160;A&#160;Ultra&#160;File&#160;View</a></span></td>
<td width="64"><span class="white">......</span></td>
<td width="48"><span class="white">9</span></td>
<td width="240"><span class="white"><a href="javascript:pressKey('@KEY:PF21');">List&#160;Of&#160;Current&#160;MANTIS&#160;Users</a></span></td>
<td width="40"><span class="white">...</span></td>
<td width="32"><span class="white">21</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="320"><span class="white"><a href="javascript:pressKey('@KEY:PF10');">Design&#160;A&#160;External&#160;File&#160;View</a>.....&#160;10</span></td>
<td width="224"><span class="white"><a href="javascript:pressKey('@KEY:PF22');">MANTIS&#160;Security&#160;Patch&#160;Info</a></span></td>
<td width="56"><span class="white">.....</span></td>
<td width="32"><span class="white">22</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="320"><span class="white"><a href="javascript:setValue('CHOICE', 'CONTROL:FACILITY-CHOICE', '101');pressKey('@KEY:ENTER');">Design&#160;A&#160;XML&#160;External&#160;File&#160;View.&#160;10.1</a></span></td>
<td width="208"><span class="white"><a href="javascript:pressKey('@KEY:PF23');">&#160;Broadcast&#160;Message</a></span></td>
<td width="72"><span class="white">.......</span></td>
<td width="32"><span class="white">23</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="176"><span class="white"><a href="javascript:setValue('CHOICE', 'CONTROL:FACILITY-CHOICE', '102');pressKey('@KEY:ENTER');">Define&#160;A&#160;WEB&#160;Service</a></span></td>
<td width="144"><span class="white">..........&#160;10.2</span></td>
<td width="224"><span class="white"><a href="javascript:pressKey('@KEY:PF24');">MANTIS&#160;Statistics&#160;Facility</a></span></td>
<td width="56"><span class="white">.....</span></td>
<td width="32"><span class="white">24</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="200"><span class="white"><a href="javascript:pressKey('@KEY:PF11');">Sign&#160;On&#160;As&#160;Another&#160;User</a></span></td>
<td width="120"><span class="white">.......&#160;11</span></td>
<td width="168"><span class="white"><a href="javascript:pressKey('@KEY:PF25');">Entity&#160;Transformers</a></span></td>
<td width="112"><span class="white">............</span></td>
<td width="32"><span class="white">25</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="152"><span class="white"><a href="javascript:pressKey('@KEY:PF12');">Transfer&#160;Facility</a></span></td>
<td width="168"><span class="white">.............&#160;12</span></td>
<td width="104"><span class="white"><a href="javascript:pressKey('@KEY:CANCEL');">Exit&#160;MANTIS</a></span></td>
<td width="144"><span class="white">................</span></td>
<td width="64"><span class="white">CANCEL</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="272"/>
<td width="16"><span class="white">:</span></td>
<td width="40"><xsl:call-template name="CHOICE"/></td>
<td width="312"><span class="white">:</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><xsl:call-template name="NOTE"/></td>
</tr></table>
</td></tr>

</tbody></table></xsl:template></xsl:stylesheet>
