<?xml version="1.0" encoding="ISO-8859-1"?>
<!--CONTROL-EXP_XML_OPTIONS-SCR.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:include href="CONTROL-EXP_XML_OPTIONS-CTX.XSL"/>
<xsl:template match="CONTROL-EXP_XML_OPTIONS">
<table align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="256"><span class="screenid">EXPX04</span></td>
<!--<td width="376"><span class="white">M&#160;A&#160;N&#160;T&#160;I&#160;S</span></td>-->
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="200"/>
<td width="440"><span class="title">UNIVERSAL&#160;EXPORT&#160;XML&#160;OPTIONS</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="96"/>
<!--<td width="384"><span class="white">XML&#160;Export&#160;Format&#160;.....................&#160;(Y/N)&#160;:</span></td>-->
<td width="284"><span class="white">XML&#160;Export&#160;Format&#160;.....................&#160;:</span></td>
<td><xsl:call-template name="XML_SCREEN_FLAG"/></td>
<!--<td width="144"><span class="white">:</span></td>-->
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="96"/>
<td width="544"><span class="white">(Exports&#160;XSL&#160;Screen&#160;Context&#160;File)</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="96"/>
<td width="284"><span class="white">Export&#160;XSL&#160;Screen&#160;Style&#160;File&#160;..........&#160;:</span></td>
<!--<td width="384"><span class="white">Export&#160;XSL&#160;Screen&#160;Style&#160;File&#160;..........&#160;(Y/N)&#160;:</span></td>-->
<td><xsl:call-template name="XSL_INCLUDE_FLAG"/></td>
<!--<td width="144"><span class="white">:</span></td>-->
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="96"/>
<td width="544"><span class="white">(Controls&#160;display&#160;of&#160;Context)</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="96"/>
<td width="544"><span class="white">___Optional&#160;Files___</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="96"/>
<!--<td width="384"><span class="white">Export&#160;XML&#160;Screen&#160;Sample&#160;File&#160;.........&#160;(Y/N)&#160;:</span></td>-->
<td width="284"><span class="white">Export&#160;XML&#160;Screen&#160;Sample&#160;File&#160;.........&#160;:</span></td>
<td><xsl:call-template name="XML_SAMPLE_FLAG"/></td>
<!--<td width="144"><span class="white">:</span></td>-->
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="96"/>
<!--<td width="384"><span class="white">Export&#160;DTD&#160;Screen&#160;Sample&#160;File&#160;.........&#160;(Y/N)&#160;:</span></td>-->
<td width="284"><span class="white">Export&#160;DTD&#160;Screen&#160;Sample&#160;File&#160;.........&#160;:</span></td>
<td><xsl:call-template name="DTD_SAMPLE_FLAG"/></td>
<!--<td width="144"><span class="white">:</span></td>-->
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="96"/>
<td width="544"><span class="white">(Sample&#160;files&#160;used&#160;as&#160;templates&#160;for&#160;import)</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="32"/>
<td width="608"><xsl:call-template name="OPT_MSG_FIELD"/></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="168"/>
<td width="472"><span class="white"><a href="javascript:pressKey('@KEY:ENTER');">ENTER</a>&#160;Update;&#160;
<a href="javascript:pressKey('@KEY:CANCEL');">CANCEL</a>&#160;Exit;&#160;
<a href="javascript:pressKey('@KEY:HELP');">GOLD/H</a>&#160;Help</span></td>
</tr></table>
</td></tr>

</tbody></table></xsl:template></xsl:stylesheet>
