<?xml version="1.0" encoding="UTF-8"?>
<!--CONTROL-EXP_FACILITY_CCB-MENU.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="html" indent="yes"/>
<xsl:include href="CONTROL-EXP_FACILITY_CCB-MENU_mantismenu.xsl"/>
<xsl:template name="CONTROL-EXP_FACILITY_CCB-MENU">

<xsl:call-template name="CONTROL-EXP_FACILITY_CCB-MENU_mantismenu"/>

</xsl:template>
</xsl:stylesheet>
