<?xml version="1.0" encoding="UTF-8"?>
<!--CONTROL-DIR_SELECT-SCR.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:template match="CONTROL-DIR_SELECT">
<table align="center" cellpadding="0" cellspacing="0"><tbody>
<!--<tr><td>&#160;</td></tr><tr><td>&#160;</td></tr>
<tr><td>
<span class="white">SEL</span>
</td></tr>-->

<xsl:choose><xsl:when test="SEL__1">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__1/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__1" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__1'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__1"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__1" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__2">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__2/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__2" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__2'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__2"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__2" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__3">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__3/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__3" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__3'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__3"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__3" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__4">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__4/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__4" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__4'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__4"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__4" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__5">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__5/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__5" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__5'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__5"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__5" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__6">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__6/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__6" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__6'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__6"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__6" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__7">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__7/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__7" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__7'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__7"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__7" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__8">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__8/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__8" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__8'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__8"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__8" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__9">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__9/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__9" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__9'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__9"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__9" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__10">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__10/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__10" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__10'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__10"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__10" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__11">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__11/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__11" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__11'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__11"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__11" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__12">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__12/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__12" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__12'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__12"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__12" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__13">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__13/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__13" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__13'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__13"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__13" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__14">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__14/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__14" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__14'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__14"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__14" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__15">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__15/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__15" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__15'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__15"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__15" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__16">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__16/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__16" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__16'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__16"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__16" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__17">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__17/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__17" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__17'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__17"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__17" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__18">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__18/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__18" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__18'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__18"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__18" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>


<xsl:choose><xsl:when test="SEL__19">
<tr><td>
<span>&#160;</span>
<xsl:choose><xsl:when test="SEL__19/@PRO='N'">
<input type="hidden" size="1" value="" name="SEL__19" class="upper" maxlength="1" onChange="modified(this,'CONTROL:DIR_SELECT-SEL__19'); validate();">
<xsl:attribute name="value"><xsl:value-of select="SEL__19"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<span class="white"><xsl:apply-templates select="SEL__19" mode="ControlWhitespace"/></span>
</xsl:otherwise></xsl:choose>
</td></tr>
</xsl:when></xsl:choose>

</tbody></table>

</xsl:template></xsl:stylesheet>
