<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-HANDICAP_PLAYER_ADD-SCR.XSL-->
<!--Generated 2016/02/03 16:04:45 FontSize="13"-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-HANDICAP_PLAYER_ADD-CTX.XSL"/>
<xsl:template match="EXAMPLES-HANDICAP_PLAYER_ADD">
<div id="scr_indicator">
<table colsizes="640" align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">PLY001</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="256"/>
<td width="32"><span class="r_b_white">&#160;M</span></td>
<td width="24"><span class="r_b_white">A</span></td>
<td width="24"><span class="r_b_white">N</span></td>
<td width="24"><span class="r_b_white">T</span></td>
<td width="24"><span class="r_b_white">I</span></td>
<td width="256"><span class="r_b_white">S</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="192"/>
<td width="448"><span class="r_b_white">&#160;Add&#160;New&#160;Player&#160;To&#160;Handicap&#160;System</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">First&#160;Name.:</span></td>
<td width="408"><xsl:call-template name="FIRST_NAME"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">Last&#160;Name..:</span></td>
<td width="408"><xsl:call-template name="LAST_NAME"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">Nick&#160;Name..:</span></td>
<td width="408"><xsl:call-template name="NICK_NAME"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">Address....:</span></td>
<td width="408"><xsl:call-template name="ADDRESS"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">City.......:</span></td>
<td width="408"><xsl:call-template name="CITY"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">State......:</span></td>
<td width="408"><xsl:call-template name="STATE"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">Zip&#160;Code...:</span></td>
<td width="408"><xsl:call-template name="ZIP_CODE"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">Home&#160;Phone.:</span></td>
<td width="408"><xsl:call-template name="HOME_PHONE"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">Work&#160;Phone.:</span></td>
<td width="408"><xsl:call-template name="WORK_PHONE"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="104"><span class="b_white">E/Mail&#160;Addr:</span></td>
<td width="408"><xsl:call-template name="EMAIL_ADDR"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><span class="white">Please&#160;fill&#160;in&#160;the&#160;above&#160;Information,&#160;only&#160;the&#160;First&#160;and&#160;Last&#160;Name</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><span class="white">is&#160;required.&#160;All&#160;other&#160;fields&#160;are&#160;optional.&#160;Once&#160;completed,&#160;press&#160;the</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><span class="white">Enter&#160;Key&#160;to&#160;add&#160;the&#160;Player&#160;Information&#160;or&#160;the&#160;Cancel&#160;Key&#160;to&#160;Exit.</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><xsl:call-template name="NOTE"/></td>
</tr></table>
</td></tr>
</tbody></table></div></xsl:template></xsl:stylesheet>
