<?xml version="1.0" encoding="UTF-8"?>
<!--EXAMPLES-GOLF_INFO_001_FORMULA-INC.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:template match="EXAMPLES-GOLF_INFO_001_FORMULA">
<table align="center"><tbody>
<tr><td>
<span>&#160;</span>
<span class="screenid">INF001</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;</span>
<span class="title">USGA HANDICAP FORMULA</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">A Handicap Index is the USGA&#39;s mark which is used to indicate a measurement</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">of a player&#39;s potential scoring ability on a course of standard difficulty.</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">Potential scoring ability is measured by a player&#39;s best scores,</span>
<span>&#160;</span>
<span class="white">and is</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">expressed as a number taken to one decimal place. These scores are identified</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">by calculating the handicap differential for each score. The USGA Handicap</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">Index is calculated by taking 96 percent of the average of the best handicap</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">differentials.</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span class="white">How to Determine Handicap Differentials</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">A handicap differential is computed from four elements:</span>
<span>&#160;</span>
<span class="white">adjusted gross</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">score, USGA Course Rating, USGA Slope Rating</span>
<span>&#160;</span>
<span class="white">and</span>
<span>&#160;</span>
<span class="white">113</span>
<span>&#160;</span>
<span class="white">(the Slope Rating</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">of a course of standard difficulty). To determine the handicap differential,</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">subtract the USGA Course Rating from the adjusted gross score; multiply</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">the difference by 113; then divide the resulting number by the USGA Slope</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">Rating. Round the final number to the nearest tenth.</span>
</td></tr>
<tr><td>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">Handicap Differential = (Adjusted Gross Score - USGA Course Rating)</span>
<span>&#160;&#160;</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">x 113 / USGA Slope Rating</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
</td></tr>
</tbody></table></xsl:template></xsl:stylesheet>
