<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-GOLF_ROUND_MORE-SCR.XSL-->
<!--Generated 2013/10/04 16:38:17 FontSize=" "-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-GOLF_ROUND_MORE-CTX.XSL"/>
<xsl:template match="EXAMPLES-GOLF_ROUND_MORE">
<div id="GOLF_ROUND_MORE__meat"><div id="scr_indicator">
	<div id="handicapIntro">
	    <div class="manRow" >
	        <div class="manField">MORE ROUNDS</div>
	        <div class="manData manSingle">
	        <xsl:call-template name="MORE_ROUNDS"/></div>
	    </div>
	</div>
    <div class="manRow" >
    </div>
</div></div></xsl:template></xsl:stylesheet>
