<?xml version="1.0" encoding="UTF-8"?>
<!--EXAMPLES-SPACE_INVADERS_SHIP-INC.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:template match="EXAMPLES-SPACE_INVADERS_SHIP">
<table align="center"><tbody>
<tr><td>
<span class="white">OO</span>
</td></tr>
<tr><td>
<span class="white">/\</span>
</td></tr>
</tbody></table></xsl:template></xsl:stylesheet>
