<?xml version="1.0" encoding="UTF-8"?>
<!--EXAMPLES-GOLF_INFO_006_IDX_OF_20-INC.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:template match="EXAMPLES-GOLF_INFO_006_IDX_OF_20">
<table align="center"><tbody>
<tr><td>
<span>&#160;</span>
<span class="screenid">INF006</span>
<span>&#160;&#160;&#160;</span>
<span class="title">Example of a Player with 20 Scores that show his USGA HDCP Index</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">Date</span>
<span>&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">USGA</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">USGA</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">Slope</span>
<span>&#160;</span>
<span class="white"></span>
<span class="white">HDCP</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">Date</span>
<span>&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">USGA</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">USGA</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">Slope</span>
<span>&#160;</span>
<span class="white"></span>
<span class="white">HDCP</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">Adjusted</span>
<span class="white"></span>
<span class="white">Course</span>
<span class="white"></span>
<span class="white">Rating</span>
<span class="white"></span>
<span class="white">Diff</span>
<span class="white"></span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">Adjusted</span>
<span class="white"></span>
<span class="white">Course</span>
<span class="white"></span>
<span class="white">Rating</span>
<span class="white"></span>
<span class="white">Diff</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">Score</span>
<span>&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">Rating</span>
<span class="white"></span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">Score</span>
<span>&#160;&#160;&#160;</span>
<span class="white"></span>
<span class="white">Rating</span>
<span class="white"></span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">9/21/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">90</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">19.4</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">9/18/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">91</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">20.4</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">9/01/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">94</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">72.3</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">123</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">19.9</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">8/29/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*88</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">17.4</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">8/28/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">89</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">18.4</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">8/16/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*90</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">72.3</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">123</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">16.3</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">8/10/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*91</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">72.3</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">123</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">17.2</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">8/01/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">91</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">20.4</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">7/29/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">91</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">20.4</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">7/15/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">86</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">68.7</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">105</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">18.6</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">7/10/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">90</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">19.4</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">7/07/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*92</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">72.3</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">123</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">18.1</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">6/27/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*85</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">68.0</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">107</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">18.0</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">6/20/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*78</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">68.7</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">105</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">10.0</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">6/14/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*82</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">11.6</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">6/07/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*84</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">13.5</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">5/01/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">94</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">72.3</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">123</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">19.9</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">3/15/00</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;&#160;</span>
<span class="white">93</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">72.3</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">123</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">19.0</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white">9/29/99</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*89</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">72.3</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">123</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">15.3</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">9/01/99</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">*88</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">70.1</span>
<span>&#160;</span>
<span class="white"></span>
<span>&#160;</span>
<span class="white">116</span>
<span>&#160;&#160;</span>
<span class="white"></span>
<span class="white">17.4</span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
<span class="white"></span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;&#160;</span>
<span class="white">Total of Lowest 10 Handicap Diff:</span>
<span>&#160;</span>
<span class="white">154.8</span>
<span>&#160;&#160;&#160;</span>
<span class="white">Avg (154.8 divided by 10&#62;&#62;:</span>
<span>&#160;</span>
<span class="white">15.48</span>
</td></tr>
<tr><td>
<span>&#160;&#160;</span>
<span class="white">Multiply average by .96&#62;&#62;&#62;&#62;&#62;&#62;&#62;&#62;&#62;:</span>
<span>&#160;</span>
<span class="white">14.861</span>
<span>&#160;&#160;</span>
<span class="white">Delete digits after tenths:</span>
<span>&#160;</span>
<span class="white">14.8</span>
</td></tr>
<tr><td>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;&#160;&#160;</span>
<span class="white">USGA Handicap Index&#62;&#62;&#62;&#62;&#62;&#62;&#62;:</span>
<span>&#160;</span>
<span class="white">14.8</span>
</td></tr>
</tbody></table></xsl:template></xsl:stylesheet>
