<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-GOLF_COURSE_DELETE-SCR.XSL-->
<!--Generated 2013/10/04 16:27:26 FontSize=" "-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-GOLF_COURSE_DELETE-CTX.XSL"/>
<xsl:template match="EXAMPLES-GOLF_COURSE_DELETE">
<div id="GOLF_COURSE_DELETE__meat"><div id="scr_indicator">
    <div class="manRow" >
        <div class="manField">COURSE NAME</div>
        <div class="manData manSingle">
        <xsl:call-template name="COURSE_NAME"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">COURSE PHONE</div>
        <div class="manData manSingle">
        <xsl:call-template name="COURSE_PHONE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">FOR TEE YARDAGE</div>
        <div class="manData manSingle">
        <xsl:call-template name="FOR_TEE_YARDAGE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">FOR TEE RATING</div>
        <div class="manData manSingle">
        <xsl:call-template name="FOR_TEE_RATING"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">FOR TEE SLOPE</div>
        <div class="manData manSingle">
        <xsl:call-template name="FOR_TEE_SLOPE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">MID TEE YARDAGE</div>
        <div class="manData manSingle">
        <xsl:call-template name="MID_TEE_YARDAGE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">MID TEE RATING</div>
        <div class="manData manSingle">
        <xsl:call-template name="MID_TEE_RATING"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">MID TEE SLOPE</div>
        <div class="manData manSingle">
        <xsl:call-template name="MID_TEE_SLOPE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">BCK TEE YARDAGE</div>
        <div class="manData manSingle">
        <xsl:call-template name="BCK_TEE_YARDAGE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">BCK TEE RATING</div>
        <div class="manData manSingle">
        <xsl:call-template name="BCK_TEE_RATING"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">BCK TEE SLOPE</div>
        <div class="manData manSingle">
        <xsl:call-template name="BCK_TEE_SLOPE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">PRO TEE YARDAGE</div>
        <div class="manData manSingle">
        <xsl:call-template name="PRO_TEE_YARDAGE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">PRO TEE RATING</div>
        <div class="manData manSingle">
        <xsl:call-template name="PRO_TEE_RATING"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">PRO TEE SLOPE</div>
        <div class="manData manSingle">
        <xsl:call-template name="PRO_TEE_SLOPE"/></div>
    </div>
    <div class="manRow" >
        <div class="manField">NOTE</div>
        <div class="manData manSingle">
        <xsl:call-template name="NOTE"/></div>
    </div>
    <div class="manRow" >
    </div>
</div></div></xsl:template></xsl:stylesheet>
