<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-GOLF_COURSE_SELECT-CTX.XSL-->
<!--Generated 2013/10/07 14:56:00 -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:template name="SEL__1">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__1/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__1/@LFA}" name="SEL__1" id="SEL__1" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__1');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__1');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__1!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__1" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__1/@HID='N'">
<span class="white">
<a name="SEL__1" id="SEL__1">
<xsl:apply-templates select="SEL__1[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__2">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__2/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__2/@LFA}" name="SEL__2" id="SEL__2" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__2');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__2');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__2!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__2" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__2/@HID='N'">
<span class="white">
<a name="SEL__2" id="SEL__2">
<xsl:apply-templates select="SEL__2[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__3">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__3/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__3/@LFA}" name="SEL__3" id="SEL__3" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__3');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__3');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__3!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__3" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__3/@HID='N'">
<span class="white">
<a name="SEL__3" id="SEL__3">
<xsl:apply-templates select="SEL__3[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__4">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__4/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__4/@LFA}" name="SEL__4" id="SEL__4" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__4');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__4');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__4!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__4" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__4/@HID='N'">
<span class="white">
<a name="SEL__4" id="SEL__4">
<xsl:apply-templates select="SEL__4[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__5">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__5/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__5/@LFA}" name="SEL__5" id="SEL__5" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__5');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__5');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__5!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__5" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__5/@HID='N'">
<span class="white">
<a name="SEL__5" id="SEL__5">
<xsl:apply-templates select="SEL__5[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__6">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__6/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__6/@LFA}" name="SEL__6" id="SEL__6" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__6');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__6');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__6!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__6" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__6/@HID='N'">
<span class="white">
<a name="SEL__6" id="SEL__6">
<xsl:apply-templates select="SEL__6[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__7">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__7/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__7/@LFA}" name="SEL__7" id="SEL__7" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__7');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__7');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__7!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__7" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__7/@HID='N'">
<span class="white">
<a name="SEL__7" id="SEL__7">
<xsl:apply-templates select="SEL__7[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__8">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__8/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__8/@LFA}" name="SEL__8" id="SEL__8" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__8');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__8');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__8!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__8" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__8/@HID='N'">
<span class="white">
<a name="SEL__8" id="SEL__8">
<xsl:apply-templates select="SEL__8[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__9">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__9/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__9/@LFA}" name="SEL__9" id="SEL__9" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__9');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__9');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__9!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__9" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__9/@HID='N'">
<span class="white">
<a name="SEL__9" id="SEL__9">
<xsl:apply-templates select="SEL__9[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__10">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__10/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__10/@LFA}" name="SEL__10" id="SEL__10" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__10');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__10');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__10!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__10" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__10/@HID='N'">
<span class="white">
<a name="SEL__10" id="SEL__10">
<xsl:apply-templates select="SEL__10[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__11">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__11/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__11/@LFA}" name="SEL__11" id="SEL__11" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__11');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__11');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__11!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__11" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__11/@HID='N'">
<span class="white">
<a name="SEL__11" id="SEL__11">
<xsl:apply-templates select="SEL__11[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__12">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__12/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__12/@LFA}" name="SEL__12" id="SEL__12" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__12');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__12');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__12!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__12" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__12/@HID='N'">
<span class="white">
<a name="SEL__12" id="SEL__12">
<xsl:apply-templates select="SEL__12[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__13">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__13/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__13/@LFA}" name="SEL__13" id="SEL__13" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__13');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__13');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__13!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__13" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__13/@HID='N'">
<span class="white">
<a name="SEL__13" id="SEL__13">
<xsl:apply-templates select="SEL__13[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="SEL__14">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="SEL__14/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="1" class="{SEL__14/@LFA}" name="SEL__14" id="SEL__14" maxlength="1"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__14');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-SEL__14');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="SEL__14!=''">
<xsl:attribute name="value">
<xsl:value-of select="SEL__14" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="SEL__14/@HID='N'">
<span class="white">
<a name="SEL__14" id="SEL__14">
<xsl:apply-templates select="SEL__14[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__1">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__1/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__1/@LFA}" name="COURSE_NAME_SELECT__1" id="COURSE_NAME_SELECT__1" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__1');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__1');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__1!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__1" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__1/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__1" id="COURSE_NAME_SELECT__1" href="javascript:setValue('SEL__1', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__1', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__1[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__2">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__2/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__2/@LFA}" name="COURSE_NAME_SELECT__2" id="COURSE_NAME_SELECT__2" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__2');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__2');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__2!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__2" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__2/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__2" id="COURSE_NAME_SELECT__2" href="javascript:setValue('SEL__2', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__2', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__2[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__3">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__3/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__3/@LFA}" name="COURSE_NAME_SELECT__3" id="COURSE_NAME_SELECT__3" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__3');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__3');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__3!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__3" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__3/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__3" id="COURSE_NAME_SELECT__3" href="javascript:setValue('SEL__3', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__3', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__3[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__4">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__4/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__4/@LFA}" name="COURSE_NAME_SELECT__4" id="COURSE_NAME_SELECT__4" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__4');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__4');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__4!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__4" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__4/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__4" id="COURSE_NAME_SELECT__4" href="javascript:setValue('SEL__4', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__4', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__4[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__5">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__5/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__5/@LFA}" name="COURSE_NAME_SELECT__5" id="COURSE_NAME_SELECT__5" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__5');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__5');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__5!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__5" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__5/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__5" id="COURSE_NAME_SELECT__5" href="javascript:setValue('SEL__5', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__5', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__5[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__6">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__6/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__6/@LFA}" name="COURSE_NAME_SELECT__6" id="COURSE_NAME_SELECT__6" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__6');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__6');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__6!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__6" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__6/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__6" id="COURSE_NAME_SELECT__6" href="javascript:setValue('SEL__6', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__6', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__6[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__7">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__7/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__7/@LFA}" name="COURSE_NAME_SELECT__7" id="COURSE_NAME_SELECT__7" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__7');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__7');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__7!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__7" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__7/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__7" id="COURSE_NAME_SELECT__7" href="javascript:setValue('SEL__7', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__7', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__7[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__8">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__8/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__8/@LFA}" name="COURSE_NAME_SELECT__8" id="COURSE_NAME_SELECT__8" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__8');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__8');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__8!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__8" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__8/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__8" id="COURSE_NAME_SELECT__8" href="javascript:setValue('SEL__8', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__8', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__8[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__9">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__9/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__9/@LFA}" name="COURSE_NAME_SELECT__9" id="COURSE_NAME_SELECT__9" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__9');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__9');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__9!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__9" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__9/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__9" id="COURSE_NAME_SELECT__9" href="javascript:setValue('SEL__9', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__9', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__9[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__10">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__10/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__10/@LFA}" name="COURSE_NAME_SELECT__10" id="COURSE_NAME_SELECT__10" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__10');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__10');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__10!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__10" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__10/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__10" id="COURSE_NAME_SELECT__10" href="javascript:setValue('SEL__10', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__10', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__10[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_NAME_SELECT__11">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__11/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="32" class="{COURSE_NAME_SELECT__11/@LFA}" name="COURSE_NAME_SELECT__11" id="COURSE_NAME_SELECT__11" maxlength="32"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__11');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_NAME_SELECT__11');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__11!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_NAME_SELECT__11" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_NAME_SELECT__11/@HID='N'">
<span class="white">
<a name="COURSE_NAME_SELECT__11" id="COURSE_NAME_SELECT__11" href="javascript:setValue('SEL__11', 'EXAMPLES:GOLF_COURSE_SELECT-SEL__11', 'S');pressKey('@KEY:ENTER');">
<xsl:apply-templates select="COURSE_NAME_SELECT__11[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__1">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__1/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__1/@LFA}" name="COURSE_PHONE_SELECT__1" id="COURSE_PHONE_SELECT__1" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__1');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__1');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__1!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__1" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__1/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__1" id="COURSE_PHONE_SELECT__1">
<xsl:apply-templates select="COURSE_PHONE_SELECT__1[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__2">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__2/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__2/@LFA}" name="COURSE_PHONE_SELECT__2" id="COURSE_PHONE_SELECT__2" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__2');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__2');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__2!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__2" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__2/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__2" id="COURSE_PHONE_SELECT__2">
<xsl:apply-templates select="COURSE_PHONE_SELECT__2[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__3">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__3/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__3/@LFA}" name="COURSE_PHONE_SELECT__3" id="COURSE_PHONE_SELECT__3" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__3');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__3');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__3!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__3" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__3/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__3" id="COURSE_PHONE_SELECT__3">
<xsl:apply-templates select="COURSE_PHONE_SELECT__3[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__4">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__4/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__4/@LFA}" name="COURSE_PHONE_SELECT__4" id="COURSE_PHONE_SELECT__4" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__4');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__4');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__4!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__4" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__4/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__4" id="COURSE_PHONE_SELECT__4">
<xsl:apply-templates select="COURSE_PHONE_SELECT__4[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__5">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__5/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__5/@LFA}" name="COURSE_PHONE_SELECT__5" id="COURSE_PHONE_SELECT__5" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__5');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__5');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__5!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__5" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__5/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__5" id="COURSE_PHONE_SELECT__5">
<xsl:apply-templates select="COURSE_PHONE_SELECT__5[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__6">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__6/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__6/@LFA}" name="COURSE_PHONE_SELECT__6" id="COURSE_PHONE_SELECT__6" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__6');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__6');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__6!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__6" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__6/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__6" id="COURSE_PHONE_SELECT__6">
<xsl:apply-templates select="COURSE_PHONE_SELECT__6[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__7">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__7/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__7/@LFA}" name="COURSE_PHONE_SELECT__7" id="COURSE_PHONE_SELECT__7" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__7');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__7');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__7!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__7" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__7/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__7" id="COURSE_PHONE_SELECT__7">
<xsl:apply-templates select="COURSE_PHONE_SELECT__7[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__8">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__8/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__8/@LFA}" name="COURSE_PHONE_SELECT__8" id="COURSE_PHONE_SELECT__8" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__8');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__8');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__8!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__8" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__8/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__8" id="COURSE_PHONE_SELECT__8">
<xsl:apply-templates select="COURSE_PHONE_SELECT__8[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__9">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__9/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__9/@LFA}" name="COURSE_PHONE_SELECT__9" id="COURSE_PHONE_SELECT__9" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__9');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__9');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__9!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__9" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__9/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__9" id="COURSE_PHONE_SELECT__9">
<xsl:apply-templates select="COURSE_PHONE_SELECT__9[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__10">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__10/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__10/@LFA}" name="COURSE_PHONE_SELECT__10" id="COURSE_PHONE_SELECT__10" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__10');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__10');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__10!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__10" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__10/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__10" id="COURSE_PHONE_SELECT__10">
<xsl:apply-templates select="COURSE_PHONE_SELECT__10[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="COURSE_PHONE_SELECT__11">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__11/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="12" class="{COURSE_PHONE_SELECT__11/@LFA}" name="COURSE_PHONE_SELECT__11" id="COURSE_PHONE_SELECT__11" maxlength="12"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__11');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-COURSE_PHONE_SELECT__11');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__11!=''">
<xsl:attribute name="value">
<xsl:value-of select="COURSE_PHONE_SELECT__11" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="COURSE_PHONE_SELECT__11/@HID='N'">
<span class="white">
<a name="COURSE_PHONE_SELECT__11" id="COURSE_PHONE_SELECT__11">
<xsl:apply-templates select="COURSE_PHONE_SELECT__11[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
<xsl:template name="NOTE">
<div id="ctx_indicator">
<xsl:choose><xsl:when test="NOTE/@PRO='N'">
<input type="text" autocomplete="on" pattern=""   value="" size="72" class="{NOTE/@LFA}" name="NOTE" id="NOTE" maxlength="72"
   onChange="modified(this,'EXAMPLES:GOLF_COURSE_SELECT-NOTE');"
   onFocus="setFocus(this,'EXAMPLES:GOLF_COURSE_SELECT-NOTE');"
   onBlur="setFocus('','');">
<xsl:choose><xsl:when test="NOTE!=''">
<xsl:attribute name="value">
<xsl:value-of select="NOTE" />
</xsl:attribute></xsl:when></xsl:choose>
</input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="NOTE/@HID='N'">
<span class="white">
<a name="NOTE" id="NOTE">
<xsl:apply-templates select="NOTE[1]" mode="ControlWhitespace"/>
</a></span></xsl:when></xsl:choose>
</xsl:otherwise>
</xsl:choose></div>
</xsl:template>
</xsl:stylesheet>
