<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-HANDICAP_INFO_008_STROKE_CNTL-SCR.XSL-->
<!--Generated 2016/02/03 16:04:41 FontSize="13"-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-HANDICAP_INFO_008_STROKE_CNTL-CTX.XSL"/>
<xsl:template match="EXAMPLES-HANDICAP_INFO_008_STROKE_CNTL">
<div id="scr_indicator">
<table colsizes="640" align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="224"><span class="white">INF008</span></td>
<td width="408"><span class="r_b_white">Adjusting&#160;Holes&#160;Scores</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">The&#160;game&#160;of&#160;golf&#160;is&#160;based&#160;on&#160;the&#160;premise&#160;that&#160;a&#160;golfer&#160;will&#160;play&#160;as&#160;well&#160;as</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">he&#160;can&#160;every&#160;time&#160;he&#160;plays.&#160;Under&#160;the&#160;USGA&#160;Handicap&#160;System&#160;he&#160;is&#160;required</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">to&#160;record&#160;a&#160;hole&#160;score&#160;for&#160;a&#160;hole&#160;he&#160;has&#160;not&#160;finished,&#160;not&#160;played,&#160;or&#160;not</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="288"><span class="white">played&#160;under&#160;the&#160;Rules&#160;of&#160;Golf,&#160;and</span></td>
<td width="200"><span class="b_white">to&#160;adjust&#160;any&#160;hole&#160;score</span></td>
<td width="144"><span class="white">when&#160;it&#160;is</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="248"><span class="b_white">higher&#160;than&#160;the&#160;maximum&#160;number</span></td>
<td width="384"><span class="white">he&#160;is&#160;allowed&#160;to&#160;post,&#160;by&#160;using&#160;the</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="b_white">Equitable&#160;Stroke&#160;Control.</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="224"/>
<td width="416"><span class="r_b_white">Equitable&#160;Stroke&#160;Control</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">Equitable&#160;Stroke&#160;Control&#160;(ESC)&#160;is&#160;the&#160;downward&#160;adjustment&#160;of&#160;individual</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">hole&#160;scores&#160;for&#160;handicap&#160;purposes&#160;in&#160;order&#160;to&#160;make&#160;handicaps&#160;more</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="448"><span class="white">representative&#160;of&#160;a&#160;player&#39;s&#160;potential&#160;scoring&#160;ability.</span></td>
<td width="184"><span class="b_white">ESC&#160;sets&#160;a&#160;maximum</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="b_white">number&#160;that&#160;a&#160;player&#160;can&#160;post&#160;on&#160;any&#160;hole&#160;depending&#160;on&#160;the&#160;player&#39;s</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="136"><span class="b_white">Course&#160;Handicap.</span></td>
<td width="496"><span class="white">ESC&#160;is&#160;used&#160;only&#160;when&#160;a&#160;player&#39;s&#160;actual&#160;or&#160;most&#160;likely</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">score&#160;exceeds&#160;his&#160;maximum&#160;number&#160;based&#160;on&#160;the&#160;table&#160;below.&#160;There&#160;is</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">no&#160;limit&#160;to&#160;the&#160;number&#160;of&#160;holes&#160;on&#160;which&#160;a&#160;player&#160;may&#160;adjust&#160;his&#160;score.</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="80"><span class="white">Press&#160;the</span></td>
<td width="80"><span class="b_white">ENTER&#160;Key</span></td>
<td width="88"><span class="white">to&#160;see&#160;the</span></td>
<td width="384"><span class="b_white">Equitable&#160;Stroke&#160;Control&#160;Table.</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
</tbody></table></div></xsl:template></xsl:stylesheet>
