<?xml version="1.0" encoding="UTF-8"?>
<!--EXAMPLES-GOLF_INFO_007_WHY.96-SCR.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:template match="EXAMPLES-GOLF_INFO_007_WHY.96">
<table align="center"><tbody>
<tr><td>
<span>&#160;</span>
<span class="screenid">INF007</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;</span>
<span class="title">Bonus for Excellence 96%</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">Bonus for Excellence</span>
<span>&#160;</span>
<span class="white">is the incentive that is built into the USGA Handicap</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">System, for players to improve their golf games. It is the term used</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">to describe the small percentage below perfect equity that is used to</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">calculate Handicap Indexes</span>
<span>&#160;</span>
<span class="white">(96%).</span>
<span>&#160;</span>
<span class="white">As your Handicap Index improves (gets</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">lower), you have a slightly better chance of placing high or winning a</span>
</td></tr>
<tr><td>
<span>&#160;</span>
<span class="white">handicap event.</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
<tr><td>
<span>&#160;</span>
</td></tr>
</tbody></table></xsl:template></xsl:stylesheet>
