<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-HANDICAP_INFO_003_MINUS_HDCP-SCR.XSL-->
<!--Generated 2016/02/03 16:04:36 FontSize="13"-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-HANDICAP_INFO_003_MINUS_HDCP-CTX.XSL"/>
<xsl:template match="EXAMPLES-HANDICAP_INFO_003_MINUS_HDCP">
<div id="scr_indicator">
<table colsizes="640" align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="208"><span class="white">INF003</span></td>
<td width="424"><span class="r_b_white">Minus&#160;Handicap&#160;Differential</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">When&#160;the&#160;adjusted&#160;gross&#160;score&#160;is&#160;lower&#160;than&#160;the&#160;USGA&#160;Course&#160;Rating,&#160;the</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">handicap&#160;differential&#160;is&#160;a&#160;negative&#160;number.&#160;Following&#160;is&#160;an&#160;example&#160;for</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="480"><span class="white">determining&#160;a&#160;differential&#160;using&#160;an&#160;adjusted&#160;gross&#160;score&#160;of</span></td>
<td width="24"><span class="b_white">69</span></td>
<td width="128"><span class="white">made&#160;on&#160;a</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="288"><span class="white">course&#160;with&#160;a&#160;USGA&#160;Course&#160;Rating&#160;of</span></td>
<td width="40"><span class="b_white">71.5</span></td>
<td width="216"><span class="white">and&#160;a&#160;USGA&#160;Slope&#160;Rating&#160;of</span></td>
<td width="88"><span class="b_white">125:</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="64"/>
<td width="344"><span class="white">Adjusted&#160;Gross&#160;Score&#160;-&#160;USGA&#160;Course&#160;Rating:</span></td>
<td width="232"><span class="b_white">69&#160;-&#160;71.5&#160;=&#160;-2.5</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="64"/>
<td width="232"><span class="white">Difference&#160;x&#160;Standard&#160;Slope:</span></td>
<td width="344"><span class="b_white">-2.5&#160;x&#160;113&#160;=&#160;-282.5</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="64"/>
<td width="232"><span class="white">Result&#160;/&#160;USGA&#160;Slope&#160;Rating:</span></td>
<td width="344"><span class="b_white">-282.5&#160;/&#160;125&#160;=&#160;-2.26</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="64"/>
<td width="272"><span class="white">Handicap&#160;Differential&#160;(rounded):</span></td>
<td width="304"><span class="b_white">-2.3</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
</tbody></table></div></xsl:template></xsl:stylesheet>
