<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-HANDICAP_COURSE_TEE_SELECT-SCR.XSL-->
<!--Generated 2016/02/03 16:04:34 FontSize="13"-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-HANDICAP_COURSE_TEE_SELECT-CTX.XSL"/>
<xsl:template match="EXAMPLES-HANDICAP_COURSE_TEE_SELECT">
<div id="scr_indicator">
<table colsizes="640" align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">CRS006</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="256"/>
<td width="32"><span class="r_b_white">&#160;M</span></td>
<td width="24"><span class="r_b_white">A</span></td>
<td width="24"><span class="r_b_white">N</span></td>
<td width="24"><span class="r_b_white">T</span></td>
<td width="24"><span class="r_b_white">I</span></td>
<td width="256"><span class="r_b_white">S</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="152"/>
<td width="488"><span class="r_b_white">&#160;Select&#160;Golf&#160;Course&#160;Tee&#160;Area&#160;For&#160;The&#160;Round</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="104"/>
<td width="104"><span class="b_white">Course&#160;Name:</span></td>
<td width="432"><xsl:call-template name="COURSE_NAME"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="120"/>
<td width="120"><span class="r_b_white">&#160;Tee</span></td>
<td width="104"><span class="r_b_white">&#160;Course</span></td>
<td width="96"><span class="r_b_white">&#160;Course</span></td>
<td width="200"><span class="r_b_white">&#160;Slope</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="120"/>
<td width="120"><span class="r_b_white">&#160;Area</span></td>
<td width="104"><span class="r_b_white">&#160;Yardage</span></td>
<td width="96"><span class="r_b_white">&#160;Rating</span></td>
<td width="200"><span class="r_b_white">&#160;Rating</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="104"/>
<td width="536"><span class="b_white">-------------------------------------------------</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="80"/>
<td width="24"><xsl:call-template name="SEL_TEE__1"/></td>
<td width="152"><xsl:call-template name="TEE__1"/></td>
<td width="104"><xsl:call-template name="YARDAGE__1"/></td>
<td width="96"><xsl:call-template name="RATING__1"/></td>
<td width="184"><xsl:call-template name="SLOPE__1"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="80"/>
<td width="24"><xsl:call-template name="SEL_TEE__2"/></td>
<td width="152"><xsl:call-template name="TEE__2"/></td>
<td width="104"><xsl:call-template name="YARDAGE__2"/></td>
<td width="96"><xsl:call-template name="RATING__2"/></td>
<td width="184"><xsl:call-template name="SLOPE__2"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="80"/>
<td width="24"><xsl:call-template name="SEL_TEE__3"/></td>
<td width="152"><xsl:call-template name="TEE__3"/></td>
<td width="104"><xsl:call-template name="YARDAGE__3"/></td>
<td width="96"><xsl:call-template name="RATING__3"/></td>
<td width="184"><xsl:call-template name="SLOPE__3"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="80"/>
<td width="24"><xsl:call-template name="SEL_TEE__4"/></td>
<td width="152"><xsl:call-template name="TEE__4"/></td>
<td width="104"><xsl:call-template name="YARDAGE__4"/></td>
<td width="96"><xsl:call-template name="RATING__4"/></td>
<td width="184"><xsl:call-template name="SLOPE__4"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><span class="white">Please&#160;enter&#160;S&#160;to&#160;the&#160;left&#160;of&#160;the&#160;Golf&#160;Course&#160;Tee&#160;Area&#160;for&#160;the&#160;Round,</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><span class="white">or&#160;the&#160;Cancel&#160;Key&#160;to&#160;Exit.</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><xsl:call-template name="NOTE"/></td>
</tr></table>
</td></tr>
</tbody></table></div></xsl:template></xsl:stylesheet>
