<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-GOLF_ROUND_DELETE_OPTION-SCR.XSL-->
<!--Generated 2013/10/04 16:35:59 FontSize=" "-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-GOLF_ROUND_DELETE_OPTION-CTX.XSL"/>
<xsl:template match="EXAMPLES-GOLF_ROUND_DELETE_OPTION">
<div id="GOLF_ROUND_DELETE_OPTION__meat"><div id="scr_indicator">
	<div id="handicapIntro">
	    <div class="manRow" >
	        <div class="manField">DELETE OPTION</div>
	        <div class="manData manSingle">
	        <xsl:call-template name="DELETE_OPTION"/></div>
	    </div>
	</div>
    <div class="manRow" >
    </div>
</div></div></xsl:template></xsl:stylesheet>
