<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-COMPOSEPROPS-SCR.XSL-->
<!--Generated 2013/01/03 16:06:02 FontSize="13"-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-COMPOSEPROPS-CTX.XSL"/>
<xsl:template match="EXAMPLES-COMPOSEPROPS">
<table colsizes="2040" align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="127"><span class="white">MAIL&#160;SERVER&#160;.&#160;.</span></td>
<td width="1905"><xsl:call-template name="MAIL_SERVER"/></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="127"><span class="white">MAIL&#160;SMTPPORT&#160;.</span></td>
<td width="1905"><xsl:call-template name="MAIL_SMTPPORT"/></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="127"><span class="white">MAIL&#160;USER&#160;.&#160;.&#160;.</span></td>
<td width="1905"><xsl:call-template name="MAIL_USER"/></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="127"><span class="white">MAIL&#160;PASS&#160;.&#160;.&#160;.</span></td>
<td width="1905"><xsl:call-template name="MAIL_PASS"/></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="80"><span class="white">MAIL&#160;SSL</span></td>
<td width="43"><span class="white">.&#160;.&#160;.</span></td>
<td width="1909"><xsl:call-template name="MAIL_SSL"/></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="80"><span class="white">MAIL&#160;TLS</span></td>
<td width="43"><span class="white">.&#160;.&#160;.</span></td>
<td width="1909"><xsl:call-template name="MAIL_TLS"/></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="2040" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="2040"/>
</tr></table>
</td></tr>
</tbody></table></xsl:template></xsl:stylesheet>
