<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-COST_STORAGE-CTX.XSL-->
<!--Generated 2022/08/22 10:32:21 -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:template name="TITLE__1">
<xsl:choose><xsl:when test="TITLE__1/@PRO='N'">
<input size="32" class="{TITLE__1/@LFA} manInput" name="TITLE__1" id="TITLE__1" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__1');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__1');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__1"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__1/@HID='N'">
<span name="TITLE__1" id="TITLE__1" maxlength="32" class="{TITLE__1/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__1[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__2">
<xsl:choose><xsl:when test="TITLE__2/@PRO='N'">
<input size="32" class="{TITLE__2/@LFA} manInput" name="TITLE__2" id="TITLE__2" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__2');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__2');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__2"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__2/@HID='N'">
<span name="TITLE__2" id="TITLE__2" maxlength="32" class="{TITLE__2/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__2[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__3">
<xsl:choose><xsl:when test="TITLE__3/@PRO='N'">
<input size="32" class="{TITLE__3/@LFA} manInput" name="TITLE__3" id="TITLE__3" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__3');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__3');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__3"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__3/@HID='N'">
<span name="TITLE__3" id="TITLE__3" maxlength="32" class="{TITLE__3/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__3[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__4">
<xsl:choose><xsl:when test="TITLE__4/@PRO='N'">
<input size="32" class="{TITLE__4/@LFA} manInput" name="TITLE__4" id="TITLE__4" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__4');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__4');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__4"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__4/@HID='N'">
<span name="TITLE__4" id="TITLE__4" maxlength="32" class="{TITLE__4/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__4[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__5">
<xsl:choose><xsl:when test="TITLE__5/@PRO='N'">
<input size="32" class="{TITLE__5/@LFA} manInput" name="TITLE__5" id="TITLE__5" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__5');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__5');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__5"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__5/@HID='N'">
<span name="TITLE__5" id="TITLE__5" maxlength="32" class="{TITLE__5/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__5[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__6">
<xsl:choose><xsl:when test="TITLE__6/@PRO='N'">
<input size="32" class="{TITLE__6/@LFA} manInput" name="TITLE__6" id="TITLE__6" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__6');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__6');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__6"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__6/@HID='N'">
<span name="TITLE__6" id="TITLE__6" maxlength="32" class="{TITLE__6/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__6[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__7">
<xsl:choose><xsl:when test="TITLE__7/@PRO='N'">
<input size="32" class="{TITLE__7/@LFA} manInput" name="TITLE__7" id="TITLE__7" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__7');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__7');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__7"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__7/@HID='N'">
<span name="TITLE__7" id="TITLE__7" maxlength="32" class="{TITLE__7/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__7[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__8">
<xsl:choose><xsl:when test="TITLE__8/@PRO='N'">
<input size="32" class="{TITLE__8/@LFA} manInput" name="TITLE__8" id="TITLE__8" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__8');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__8');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__8"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__8/@HID='N'">
<span name="TITLE__8" id="TITLE__8" maxlength="32" class="{TITLE__8/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__8[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__9">
<xsl:choose><xsl:when test="TITLE__9/@PRO='N'">
<input size="32" class="{TITLE__9/@LFA} manInput" name="TITLE__9" id="TITLE__9" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__9');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__9');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__9"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__9/@HID='N'">
<span name="TITLE__9" id="TITLE__9" maxlength="32" class="{TITLE__9/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__9[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__10">
<xsl:choose><xsl:when test="TITLE__10/@PRO='N'">
<input size="32" class="{TITLE__10/@LFA} manInput" name="TITLE__10" id="TITLE__10" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__10');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__10');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__10"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__10/@HID='N'">
<span name="TITLE__10" id="TITLE__10" maxlength="32" class="{TITLE__10/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__10[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__11">
<xsl:choose><xsl:when test="TITLE__11/@PRO='N'">
<input size="32" class="{TITLE__11/@LFA} manInput" name="TITLE__11" id="TITLE__11" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__11');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__11');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__11"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__11/@HID='N'">
<span name="TITLE__11" id="TITLE__11" maxlength="32" class="{TITLE__11/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__11[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__12">
<xsl:choose><xsl:when test="TITLE__12/@PRO='N'">
<input size="32" class="{TITLE__12/@LFA} manInput" name="TITLE__12" id="TITLE__12" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__12');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__12');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__12"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__12/@HID='N'">
<span name="TITLE__12" id="TITLE__12" maxlength="32" class="{TITLE__12/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__12[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__13">
<xsl:choose><xsl:when test="TITLE__13/@PRO='N'">
<input size="32" class="{TITLE__13/@LFA} manInput" name="TITLE__13" id="TITLE__13" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__13');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__13');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__13"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__13/@HID='N'">
<span name="TITLE__13" id="TITLE__13" maxlength="32" class="{TITLE__13/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__13[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__14">
<xsl:choose><xsl:when test="TITLE__14/@PRO='N'">
<input size="32" class="{TITLE__14/@LFA} manInput" name="TITLE__14" id="TITLE__14" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__14');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__14');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__14"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__14/@HID='N'">
<span name="TITLE__14" id="TITLE__14" maxlength="32" class="{TITLE__14/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__14[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
<xsl:template name="TITLE__15">
<xsl:choose><xsl:when test="TITLE__15/@PRO='N'">
<input size="32" class="{TITLE__15/@LFA} manInput" name="TITLE__15" id="TITLE__15" maxlength="32" manio="true"
   onKeyPress="this.onchange();"
   onChange="modified(this,'EXAMPLES:COST_STORAGE-TITLE__15');"
   onFocus="setFocus(this,'EXAMPLES:COST_STORAGE-TITLE__15');"
   onBlur="setFocus('','');">
<xsl:attribute name="value"><xsl:value-of select="TITLE__15"/>
</xsl:attribute></input></xsl:when>
<xsl:otherwise>
<xsl:choose><xsl:when test="TITLE__15/@HID='N'">
<span name="TITLE__15" id="TITLE__15" maxlength="32" class="{TITLE__15/@LFA} manOutput" manio="true">
<xsl:apply-templates select="TITLE__15[1]" mode="ControlWhitespace"/>
</span></xsl:when></xsl:choose>
</xsl:otherwise></xsl:choose>
</xsl:template>
</xsl:stylesheet>
