<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-HANDICAP_INFO_009_STROKE_TBL-SCR.XSL-->
<!--Generated 2016/02/03 16:04:42 FontSize="13"-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-HANDICAP_INFO_009_STROKE_TBL-CTX.XSL"/>
<xsl:template match="EXAMPLES-HANDICAP_INFO_009_STROKE_TBL">
<div id="scr_indicator">
<table colsizes="640" align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="160"><span class="white">INF009</span></td>
<td width="472"><span class="r_b_white">Equitable&#160;Stroke&#160;Control&#160;Table</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="192"/>
<td width="112"><span class="b_white">Player</span></td>
<td width="336"><span class="b_white">Maximum&#160;Number</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="160"/>
<td width="144"><span class="b_white">Course&#160;Handicap</span></td>
<td width="336"><span class="b_white">On&#160;Any&#160;Hole</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="160"/>
<td width="144"><span class="b_white">9&#160;or&#160;Less</span></td>
<td width="336"><span class="b_white">Double&#160;Bogey*</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="160"/>
<td width="144"><span class="b_white">10&#160;through&#160;19</span></td>
<td width="336"><span class="b_white">7</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="160"/>
<td width="144"><span class="b_white">20&#160;through&#160;29</span></td>
<td width="336"><span class="b_white">8</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="160"/>
<td width="144"><span class="b_white">30&#160;through&#160;39</span></td>
<td width="336"><span class="b_white">9</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="160"/>
<td width="144"><span class="b_white">40&#160;or&#160;More</span></td>
<td width="336"><span class="b_white">10</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="56"><span class="b_white">*Note:</span></td>
<td width="576"><span class="white">The&#160;Double&#160;Bogey&#160;ESC&#160;proccedure&#160;listed&#160;in&#160;the&#160;first&#160;row&#160;for&#160;9&#160;or&#160;Less</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">Course&#160;Handicap&#160;was&#160;optional&#160;in&#160;1998,&#160;but&#160;became&#160;mandatory&#160;January&#160;1,1999.</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="72"><span class="b_white">Example:</span></td>
<td width="560"><span class="white">A&#160;player&#160;with&#160;a&#160;Course&#160;Handicap&#160;of&#160;13&#160;has&#160;a&#160;maximun&#160;of&#160;7&#160;for&#160;any</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">hole&#160;regardless&#160;of&#160;par.</span></td>
</tr></table>
</td></tr>
</tbody></table></div></xsl:template></xsl:stylesheet>
