<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-HANDICAP_COURSE_SELECT-SCR.XSL-->
<!--Generated 2016/02/03 16:04:33 FontSize="13"-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-HANDICAP_COURSE_SELECT-CTX.XSL"/>
<xsl:template match="EXAMPLES-HANDICAP_COURSE_SELECT">
<div id="scr_indicator">
<table colsizes="640" align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="632"><span class="white">CRS005</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="256"/>
<td width="32"><span class="r_b_white">&#160;M</span></td>
<td width="24"><span class="r_b_white">A</span></td>
<td width="24"><span class="r_b_white">N</span></td>
<td width="24"><span class="r_b_white">T</span></td>
<td width="24"><span class="r_b_white">I</span></td>
<td width="256"><span class="r_b_white">S</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="216"/>
<td width="216"><span class="r_b_white">Golf&#160;Course&#160;Names</span></td>
<td width="208"><span class="r_b_white">Phone&#160;Number</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__1"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__1"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__1"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__2"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__2"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__2"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__3"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__3"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__3"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__4"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__4"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__4"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__5"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__5"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__5"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__6"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__6"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__6"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__7"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__7"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__7"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__8"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__8"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__8"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__9"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__9"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__9"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__10"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__10"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__10"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="128"/>
<td width="24"><xsl:call-template name="SEL__11"/></td>
<td width="280"><xsl:call-template name="COURSE_NAME_SELECT__11"/></td>
<td width="208"><xsl:call-template name="COURSE_PHONE_SELECT__11"/></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><span class="white">Please&#160;enter&#160;S&#160;to&#160;the&#160;left&#160;of&#160;the&#160;Golf&#160;Course&#160;Name&#160;to&#160;be&#160;Selected,</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><span class="white">or&#160;press&#160;the&#160;Cancel&#160;Key&#160;to&#160;Exit.</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="624"><xsl:call-template name="NOTE"/></td>
</tr></table>
</td></tr>
</tbody></table></div></xsl:template></xsl:stylesheet>
