<?xml version="1.0" encoding="UTF-8"?>
<!--EXAMPLES-GOLF_INFO_004_IDX_FORMULA-INC.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:template match="EXAMPLES-GOLF_INFO_004_IDX_FORMULA">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tbody>
<tr>
  <td>
<span>&#160;</span>
<span class="screenid">INF004</span>
<span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</span>
<span>&#160;&#160;</span>
<span class="title">USGA Handicap Index Formula</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">The</span>
<span>&#160;</span>
<span class="white">USGA Handicap Index Formula</span>
<span>&#160;</span>
<span class="white">is based on the best handicap differentials</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">in a player&#39;s scoring record. If a player&#39;s scoring record contains</span>
<span>&#160;</span>
<span class="white">20 or</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">more scores,</span>
<span>&#160;</span>
<span class="white">then the</span>
<span>&#160;</span>
<span class="white">best 10 handicap differentials</span>
<span>&#160;</span>
<span class="white">of the most recent</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">20 scores</span>
<span>&#160;</span>
<span class="white">are used to calculate his</span>
<span>&#160;</span>
<span class="white">USGA Handicap Index.</span>
<span>&#160;</span>
<span class="white">The percentage</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">of scores used in a scoring record decreases from the maximum of the best</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">50 percent as the number of scores in the scoring record decreases. If the</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">scoring record contains 9 or 10 scores, then only the best three scores (30</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">to 33 percent) in the scoring record will be used. Thus, the accuracy of a</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">player&#39;s</span>
<span>&#160;</span>
<span class="white">Handicap Index</span>
<span>&#160;</span>
<span class="white">is directly proportional to the number of acceptable</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">scores he has posted. A</span>
<span>&#160;</span>
<span class="white">USGA Handicap Index</span>
<span>&#160;</span>
<span class="white">shall not be issued to a player</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">who has returned</span>
<span>&#160;</span>
<span class="white">fewer than five acceptable scores.</span>
<span>&#160;</span>
<span class="white">The following procedure</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">illustrates how authorized golf associations and golf clubs calculate a</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">player&#39;s Handicap Index if the number of acceptable scores in the player&#39;</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">record is fewer than 20.</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">Press the</span>
<span>&#160;</span>
<span class="white">Enter Key</span>
<span>&#160;</span>
<span class="white">to see Table to determined the</span>
<span>&#160;</span>
<span class="white">Number of Handicap</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
<span class="white">Differentials</span>
<span>&#160;</span>
<span class="white">to use;</span>
  </td>
</tr>
<tr>
  <td>
<span>&#160;</span>
  </td>
</tr>
</tbody>
</table>
</xsl:template>
</xsl:stylesheet>

