<?xml version="1.0" encoding="ISO-8859-1"?>
<!--EXAMPLES-HANDICAP_INFO_006_IDX_OF_20-SCR.XSL-->
<!--Generated 2016/02/03 16:04:40 FontSize="13"-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="ISO-8859-1" indent="yes"/>
<xsl:include href="EXAMPLES-HANDICAP_INFO_006_IDX_OF_20-CTX.XSL"/>
<xsl:template match="EXAMPLES-HANDICAP_INFO_006_IDX_OF_20">
<div id="scr_indicator">
<table colsizes="640" align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="72"><span class="white">INF006</span></td>
<td width="560"><span class="r_b_white">Example&#160;of&#160;a&#160;Player&#160;with&#160;20&#160;Scores&#160;that&#160;show&#160;his&#160;USGA&#160;HDCP&#160;Index</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="24"/>
<td width="64"><span class="b_white">Date</span></td>
<td width="72"><span class="b_white">USGA</span></td>
<td width="56"><span class="b_white">USGA</span></td>
<td width="56"><span class="b_white">Slope</span></td>
<td width="64"><span class="b_white">HDCP</span></td>
<td width="64"><span class="b_white">Date</span></td>
<td width="72"><span class="b_white">USGA</span></td>
<td width="56"><span class="b_white">USGA</span></td>
<td width="56"><span class="b_white">Slope</span></td>
<td width="56"><span class="b_white">HDCP</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="88"/>
<td width="72"><span class="b_white">Adjusted</span></td>
<td width="56"><span class="b_white">Course</span></td>
<td width="56"><span class="b_white">Rating</span></td>
<td width="128"><span class="b_white">Diff</span></td>
<td width="72"><span class="b_white">Adjusted</span></td>
<td width="56"><span class="b_white">Course</span></td>
<td width="56"><span class="b_white">Rating</span></td>
<td width="56"><span class="b_white">Diff</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="88"/>
<td width="72"><span class="b_white">Score</span></td>
<td width="240"><span class="b_white">Rating</span></td>
<td width="72"><span class="b_white">Score</span></td>
<td width="168"><span class="b_white">Rating</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="88"><span class="b_white">9/21/00</span></td>
<td width="64"><span class="b_white">90</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">19.4</span></td>
<td width="88"><span class="b_white">9/18/00</span></td>
<td width="64"><span class="b_white">91</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">20.4</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="88"><span class="b_white">9/01/00</span></td>
<td width="64"><span class="b_white">94</span></td>
<td width="56"><span class="b_white">72.3</span></td>
<td width="48"><span class="b_white">123</span></td>
<td width="56"><span class="b_white">19.9</span></td>
<td width="80"><span class="b_white">8/29/00</span></td>
<td width="72"><span class="b_white">*88</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">17.4</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="88"><span class="b_white">8/28/00</span></td>
<td width="64"><span class="b_white">89</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">18.4</span></td>
<td width="80"><span class="b_white">8/16/00</span></td>
<td width="72"><span class="b_white">*90</span></td>
<td width="56"><span class="b_white">72.3</span></td>
<td width="48"><span class="b_white">123</span></td>
<td width="56"><span class="b_white">16.3</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="80"><span class="b_white">8/10/00</span></td>
<td width="72"><span class="b_white">*91</span></td>
<td width="56"><span class="b_white">72.3</span></td>
<td width="48"><span class="b_white">123</span></td>
<td width="56"><span class="b_white">17.2</span></td>
<td width="88"><span class="b_white">8/01/00</span></td>
<td width="64"><span class="b_white">91</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">20.4</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="88"><span class="b_white">7/29/00</span></td>
<td width="64"><span class="b_white">91</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">20.4</span></td>
<td width="88"><span class="b_white">7/15/00</span></td>
<td width="64"><span class="b_white">86</span></td>
<td width="56"><span class="b_white">68.7</span></td>
<td width="48"><span class="b_white">105</span></td>
<td width="56"><span class="b_white">18.6</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="88"><span class="b_white">7/10/00</span></td>
<td width="64"><span class="b_white">90</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">19.4</span></td>
<td width="80"><span class="b_white">7/07/00</span></td>
<td width="72"><span class="b_white">*92</span></td>
<td width="56"><span class="b_white">72.3</span></td>
<td width="48"><span class="b_white">123</span></td>
<td width="56"><span class="b_white">18.1</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="80"><span class="b_white">6/27/00</span></td>
<td width="72"><span class="b_white">*85</span></td>
<td width="56"><span class="b_white">68.0</span></td>
<td width="48"><span class="b_white">107</span></td>
<td width="56"><span class="b_white">18.0</span></td>
<td width="80"><span class="b_white">6/20/00</span></td>
<td width="72"><span class="b_white">*78</span></td>
<td width="56"><span class="b_white">68.7</span></td>
<td width="48"><span class="b_white">105</span></td>
<td width="56"><span class="b_white">10.0</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="80"><span class="b_white">6/14/00</span></td>
<td width="72"><span class="b_white">*82</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">11.6</span></td>
<td width="80"><span class="b_white">6/07/00</span></td>
<td width="72"><span class="b_white">*84</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">13.5</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="88"><span class="b_white">5/01/00</span></td>
<td width="64"><span class="b_white">94</span></td>
<td width="56"><span class="b_white">72.3</span></td>
<td width="48"><span class="b_white">123</span></td>
<td width="56"><span class="b_white">19.9</span></td>
<td width="88"><span class="b_white">3/15/00</span></td>
<td width="64"><span class="b_white">93</span></td>
<td width="56"><span class="b_white">72.3</span></td>
<td width="48"><span class="b_white">123</span></td>
<td width="56"><span class="b_white">19.0</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="80"><span class="b_white">9/29/99</span></td>
<td width="72"><span class="b_white">*89</span></td>
<td width="56"><span class="b_white">72.3</span></td>
<td width="48"><span class="b_white">123</span></td>
<td width="56"><span class="b_white">15.3</span></td>
<td width="80"><span class="b_white">9/01/99</span></td>
<td width="72"><span class="b_white">*88</span></td>
<td width="56"><span class="b_white">70.1</span></td>
<td width="48"><span class="b_white">116</span></td>
<td width="56"><span class="b_white">17.4</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="272"><span class="white">Total&#160;of&#160;Lowest&#160;10&#160;Handicap&#160;Diff:</span></td>
<td width="64"><span class="b_white">154.8</span></td>
<td width="224"><span class="white">Avg&#160;(154.8&#160;divided&#160;by&#160;10&#62;&#62;:</span></td>
<td width="64"><span class="b_white">15.48</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="16"/>
<td width="272"><span class="white">Multiply&#160;average&#160;by&#160;.96&#62;&#62;&#62;&#62;&#62;&#62;&#62;&#62;&#62;:</span></td>
<td width="64"><span class="b_white">14.861</span></td>
<td width="224"><span class="white">Delete&#160;digits&#160;after&#160;tenths:</span></td>
<td width="64"><span class="b_white">14.8</span></td>
</tr></table>
</td></tr>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="352"/>
<td width="224"><span class="white">USGA&#160;Handicap&#160;Index&#62;&#62;&#62;&#62;&#62;&#62;&#62;:</span></td>
<td width="64"><span class="b_white">14.8</span></td>
</tr></table>
</td></tr>
</tbody></table></div></xsl:template></xsl:stylesheet>
