<?xml version="1.0" encoding="ISO-8859-1"?>
<!--MASTER-EXAMPLES_FACILITY-SCR_tabs.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:template name="MASTER-EXAMPLES_FACILITY_tabs">

<table align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="608"><span class="screenid">FAC003</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>
<tr><td>
<table width="640" cellpadding="10" cellspacing="0">
<tr><td align="center" class="title">MANTIS Server WEB FACILITIES
</td></tr>
<tr><td align="left" width="620" class="title">
Select a tab to complete a task.  Drag a tab to the top of the group of your choice.  <br/>Use the 'Favorites Group' for your commonly accessed facilities.
</td></tr>
<tr></tr>
<tr><td align="left" width="620" class="title">
Select by clicking the tab, using menus items (that group related facilities), or by choosing the number associated with the task, below.
</td></tr>
</table>
</td></tr>
</tbody></table>

</xsl:template>
</xsl:stylesheet>
