<?xml version="1.0" encoding="ISO-8859-1"?>
<!--MASTER-FACILITY-SCR_tabs.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" indent="yes"/>
<xsl:template name="MASTER-FACILITY_tabs">

<table align="center" cellpadding="0" cellspacing="0"><tbody>
<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="8"/>
<td width="608"><span class="screenid">FAC005</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="240"/>
<td width="400"><span class="title">FACILITY&#160;SELECTION</span></td>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td align="left" width="620" class="title">
  Select a tab to complete a task.
</td></tr>

<tr><td>
  <span>&#160;</span>
</td></tr>

<tr><td align="left" width="620" class="title">
  Select by clicking the tab, using menus items (that group related facilities),
  <br/>or by choosing the number associated with the task, below.
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

<tr><td>
<table border="0" width="640" align="left" cellpadding="0" cellspacing="0"><tr align="left">
<td width="640"/>
</tr></table>
</td></tr>

</tbody></table>
</xsl:template>
</xsl:stylesheet>
