<?xml version="1.0" encoding="UTF-8"?>
<!--MASTER-EXAMPLES_FACILITY-MENU.XSL-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="html" indent="yes"/>
<xsl:include href="MASTER-EXAMPLES_FACILITY-MENU_mantismenu.xsl"/>
<xsl:template name="MASTER-EXAMPLES_FACILITY-MENU">

<xsl:call-template name="MASTER-EXAMPLES_FACILITY-MENU_mantismenu"/>

</xsl:template>
</xsl:stylesheet>
